name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build RPM package
      id: rpm
      uses: zhullyb/rpmbuild@master
      with:
        spec_file: "dingtalk-bin.spec"

    - name: Upload artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ${{ steps.rpm.outputs.rpm_dir_path }}/x86_64/*.rpm
